### PR TITLE
Neil updates

### PR DESCRIPTION
**Pull request by jbwillis**
* Moved radio and flat flex connectors to get them away from board edges
* General schematic clean up

### CODE REVIEW

**Comment by jbwillis** [comment]
@NeilKhera Here's my review

* The schematic looks so much better. Thanks for getting it cleaned up.
* The location of the flat flex connector and radio seem good

Things I see that still need to be done:
- [x] Move the UFL connector (J6) to be on the same side as the radio - place it just above the "mini" bubble on the back  - location is flexible.
- [x] Shift the USB connector out away from the board in the (PCB coordinates) -X direction (see screenshot) 1.5mm. Ok to add "porch" of PCB for connector to sit on.
- [x] Swap the flat flex camera connector for a 2x5 1.27mm surface mount header (see image for location). The location on this board is fairly flexible since we'll have to also place it on the camera board. But comparing with the camera board, this seems like a good spot to put it in.


### USB Port
Screen Shot 2022-02-22 at 12 37 34 PM

### Camera connector
Screen Shot 2022-02-22 at 12 29 59 PM

**Comment by NeilKhera** [comment]
Done, please review :)

**Comment by jbwillis** [comment]
Looks good. One more request. Let's swap the 2x2 RBF header for a 1x5 header with pins as follows

1 GND
2 No Connect
3 BATT_P
4 +3V3
5 Pin 5/VOUT of U7

This will be accessible through the USB hole on the Z board opposite the USB connector, so make sure it lies in the same space as the USB connector.

Screen Shot 2022-02-23 at 10 01 41 AM

**Comment by jbwillis** [comment]
I noticed a few issues with the rf trace. For this one, I think we need to have a solid ground plane under the trace, so the two traces I circled need to be moved so they don't cut under the antenna trace. Also, there is a stub sticking out from the radio pad.

Feel free to move the UFL connector closer to the radio to resolve this as well.

Screen Shot 2022-02-25 at 9 46 49 AM

**Comment by jbwillis** [comment]
There also needs to be a ground pour on the internal layer 2.

**Comment by NeilKhera** [comment]
Is there a reason we have switch to a 1x5 header only to have one of the pins be NC?

**Comment by jbwillis** [comment]
Two reasons. First, we need the 1x to avoid interference with the camera
usb when it gets moved. Second, right now the connector is symmetric and if
a jumper in it is rotated, power and ground could be easily shorted. The NC
makes the connector asymmetric. We’ll put a dot of glue in it and trim the
corresponding pin on the matching connector. So there will only be one way
to install it.

**Comment by NeilKhera** [comment]
Great point shall do!

**Comment by NeilKhera** [comment]
Made a bunch of changes to the Rf antenna placement and routing using this article http://iot-bits.com/simple-rf-pcb-layout-tips-tricks/

**Comment by jbwillis** [comment]
This is looking good. Just a couple minor comments, PR approved when these are done!

- Swap the 5 pin male header for a female header (mostly for the 3D model)
- Make sure to increment the version #

**Comment by NeilKhera** [comment]
Do horizontal pin receptacles even exist?

**Comment by jbwillis** [comment]
https://www.digikey.com/en/products/detail/sullins-connector-solutions/LPPB051NGCN-RC/1786388

**Comment by jbwillis** [comment]
@NeilKhera Were there any changes that need to be made for out of stock components? (In particular the flat flex connector)

**Comment by NeilKhera** [comment]
The flat flex connector seems to be in stock on Newark
https://www.newark.com/omron-electronic-components/xf2m-2415-1a/connector-fpc-rcpt-24pos-0-5mm/dp/10P3869?CMP=AFC-OP
I don't know if this is a reliable website

**Pull request merged**
