### PR TITLE
Mainboard v03 Stack Updates

### PR DESCRIPTION
**Pull request by NeilKhera**
New Board Outline.
Added Bus Protections.
Added Stack Connector.
Added 4 Solar Panel Connectors.

### CODE REVIEW

**Comment by jbwillis** [comment]
This is looking good, I'm impressed you got everything on there!

ToDos:
- [x] I updated the board outline to shift the standoffs out towards the outside edge a bit. The new outline is in the repo as `mainboard-outline.dxf`. Please update the outline to match.
- [x] Needs radio 3D model
- [x] Needs USB-C 3D model
- [x] 3D models for solar panel connectors should be present, rather than the flatsat ones.

Comments/Questions:
- [x] I think the main thing that this needs is finalizing what connectors we will be using and exactly where they will be going.
- [x] Is the bus protection necessary for the Flash memory since it is the only thing on that bus?
- [x] We should consider adding a "porch" for the USB-C connector to get it out far enough for easy connection.
- [x] The double connectors for enabling "flatsat mode" are really clever. I'm not sure if it meets our use-case though (we should discuss this more). Ideally we could take a flight ready board, install it in the flatsat for testing, then (without modification) use it in a pocketqube assembly. This does provide us with long-term flatsat capability for development, and I like that. An idea I had was to keep the connectors pointing off the edges of the board and then install right angle pin-pin connectors that would then slide into connectors on the flatsat.
- [x] Why is it necessary for VBUS to go to the Solar panels?

**Comment by NeilKhera** [comment]
Moved the Standoff mounting holes back as requested

**Comment by g-savant** [comment]
Edits made: Changed board outline to match the Stack Assembly model in Fusion. Repositioned and rerouted components on board. Added microSD card reader and associated circuitry.

**Comment by jbwillis** [comment]
Have you thought about how far back the X/Z solar connectors need to be placed from the board edge to connect with the X/Z boards? Looking at the docs for the harting connectors it looks like it needs to be 8.75mm minimum to use the mating connector on the X/Z boards. Or, were you planning on using a different connector on the solar boards?

Also, looking at[ the datasheet](https://b2b.harting.com/files/download/PRD/PDF_DS/PDF_DS_15152200301_.pdf?siteName=Ebusiness+Site&autoLogoutEnabled=true&autoLogoutTime=1800&showPrivacyEmailAgreement=false&contextURL=https%3A%2F%2Fb2b.harting.com%2Febusiness%2Fen_us&maintenanceAnnounceme), it looks like the harting connectors need to "hang off" the pcb so the mating connector doesn't hit the mainboard PCB.

**Comment by jbwillis** [comment]
I am also concerned that the radio and the standoffs are going to interfere: 
image

**Comment by jbwillis** [comment]
Approved

**Pull request merged**
